# Generated by Django 3.1.3 on 2020-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
