# Generated by Django 3.1.3 on 2020-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='coordinates',
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, choices=[('PA', 'Dog Park'), ('RE', 'Restaurant'), ('VE', 'Veterinarian'), ('TR', 'Trail'), ('HO', 'House')], default='PA', max_length=2, null=True),
        ),
    ]
