# Generated by Django 3.1.3 on 2020-11-15 18:07

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (35.921637, -79.077887), 'id': 'map', 'navigation_buttons': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/streets-v11', 'track_location_button': True, 'zoom': 5}),
        ),
    ]
