# Generated by Django 3.1.3 on 2020-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201106_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate_is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
