# Generated by Django 3.1.3 on 2020-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201107_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
