# Generated by Django 3.1.3 on 2020-11-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convo_name', models.CharField(default='New Conversation', max_length=63)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminconversations', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('breed', models.CharField(max_length=63)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], default='M', max_length=3)),
                ('energy', models.CharField(choices=[('HI', 'High Energy'), ('MD', 'Medium Energy'), ('LO', 'Low Energy')], default='MD', max_length=2)),
                ('temper', models.CharField(choices=[('AGR', 'Aggressive'), ('NML', 'Normal'), ('CHL', 'Relaxed')], default='NML', max_length=3)),
                ('group_size', models.CharField(choices=[('ONE', 'ONE ON ONE'), ('BIG', 'GOOD IN LARGE GROUPS'), ('SML', 'GOOD IN SMALL GROUPS'), ('ANY', 'GOOD IN ANY SETTING')], default='ONE', max_length=3)),
                ('vaccinated', models.CharField(choices=[('YES', 'VACCINATED'), ('NOT', 'I AM TERRIBLE DOG OWNER')], default='YES', max_length=3)),
                ('kid_friendly', models.CharField(choices=[('Y', 'GOOD WITH CHILDREN'), ('N', 'NOT GOOD WITH CHILDREN')], default='Y', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('proposing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_sent', to=settings.AUTH_USER_MODEL)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('font_style', models.CharField(choices=[('N', 'Normal'), ('I', 'Italics'), ('B', 'Bold'), ('U', 'Underline')], default='N', max_length=1)),
                ('text_align', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center'), ('J', 'Justified')], default='L', max_length=1)),
                ('font_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'Xtra Large')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.dog')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(blank=True, related_name='post', to='api.Reaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('reactions', models.ManyToManyField(blank=True, related_name='message', to='api.Reaction')),
                ('read_by', models.ManyToManyField(blank=True, related_name='messages_read', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetupsadmin', to=settings.AUTH_USER_MODEL)),
                ('attending', models.ManyToManyField(related_name='meetups', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='maps.location')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
