# Generated by Django 3.1.3 on 2020-11-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
