# Generated by Django 3.1.3 on 2020-11-07 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_reaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('font_style', models.CharField(choices=[('N', 'Normal'), ('I', 'Italics'), ('B', 'Bold'), ('U', 'Underline')], default='N', max_length=1)),
                ('text_align', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center'), ('J', 'Justified')], default='L', max_length=1)),
                ('font_size', models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large'), (3, 'Xtra Large')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.dog')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
