# Generated by Django 3.1.3 on 2020-11-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201110_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='post', to='api.Reaction'),
        ),
    ]
