# Generated by Django 3.1.3 on 2020-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='num_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='num_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
