# Generated by Django 3.1.3 on 2020-11-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to='api.message'),
        ),
    ]
