# Generated by Django 3.1.3 on 2020-11-15 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201112_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionboard',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='discussionboard',
            name='upvote',
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
