# Generated by Django 3.1.3 on 2020-11-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201112_2028'),
        ('api', '0005_auto_20201113_1518'),
    ]

    operations = [
    ]
