# Generated by Django 3.1.3 on 2020-11-14 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_merge_20201114_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionboard',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='discussionboard',
            name='upvote',
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
