# Generated by Django 3.1.3 on 2020-11-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_created_at'),
        ('api', '0008_auto_20201114_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='maps.location'),
        ),
    ]
