# Generated by Django 3.1.3 on 2020-11-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201115_1618'),
        ('api', '0010_auto_20201114_2206'),
    ]

    operations = [
    ]
