# Generated by Django 3.1.3 on 2020-11-23 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_notification_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
